### ISSUE TITLE
codegen: add option to box Message fields

### ISSUE THREAD

**Issue by edre** [tokio-rs/prost#13]
If I have a protocol version 1:

```
    message B {
      int64 num = 1;
    }
    message A {
      B sub = 1;
    }
```

The generated code will inline the B struct into the A struct, and my code using it will access the field directly.

If I then release version 2 that introduces recursion:
```
    message B {
      int64 num = 1;
      A recurse = 2;
    }
    message A {
      B sub = 1;
    }
```

My code using the old generated API won't even compile when updating to the new version, which just adds a field to a proto I might not even be using directly.

As a separate concern, as someone who spends a lot of time optimizing C++ code that uses a lot of protobufs, many proto designs assume that unused submessages will take up minimal space when not used (i.e. by being empty references) and inlining them would lead to a lot more memory usage. It's at least worth mentioning somewhere in the docs that the default of inlining submessages is a very different memory tradeoff than all of the other proto implementations I've seen.

**Comment by danburkert** [comment]
(I've updated your comment to add code fences for formatting)

**Comment by danburkert** [comment]
> My code using the old generated API won't even compile when updating to the new version, which just adds a field to a proto I might not even be using directly.

So there's two issues at play here: whether the messages are compatible on the wire (the protobuf compatibility guarantees), and whether the generated code is backwards compatible (Rust source compatibility guarantees).  In terms of the first, `prost` has the same guarantees that any other protobuf library has.  For the second, no guarantees are made.  Just as renaming a field in a protobuf struct will result in changing the generated code, so will adding mutual recursion.  That being said, in this case a lot of uses _will_ be source compatible due to Rust's auto-dereferencing features.

I've personally never seen recursive, much less co-recursive, messages in real production systems, so I don't consider this a particularly compelling concern.  I mostly implemented the auto-boxing feature in order to pass the Protobuf conformance tests.

> As a separate concern, as someone who spends a lot of time optimizing C++ code that uses a lot of protobufs, many proto designs assume that unused submessages will take up minimal space when not used (i.e. by being empty references) and inlining them would lead to a lot more memory usage

Yes, it's possible, or likely, that `prost` message types will be bigger than their counterpart generated from the C++ library.  `prost` could add a way to opt-in to boxing in generated code.  The flip side is that `prost` will do much less allocation when the nested messages are filled in.  I'm fairly confident that unboxed structs are the correct default.

**Comment by danburkert** [comment]
Going to repurpose this issue to track adding an option for boxing message fields during codegen.  The implementation should be straightforward, cb985d8dd518cfac11ebc49601d2eaf3468143a1 is an example of adding a similar config.  The only unknown is whether this should be configurable on a per type basis, or on a per field basis.  My intuition is that it should be configured on a per-type basis (so large types can be boxed wherever they are used as fields), but since I haven't run into a situation where I'd want to box, I'm not entirely sure.
