### ISSUE TITLE
Generating rust code in a stand-alone fashion?

### ISSUE THREAD

**Issue by photex** [tokio-rs/prost#354]
Howdy!

Code generation always happening via build.rs is sometimes nice but is it possible to not require this and instead use ahead of time generated code?

**Comment by cetanu** [comment]
When you run cargo build it should generate some files in the target folder... you could technically copy these into your src directory and use them I guess

**Comment by greg-szabo** [comment]
I'm doing something like that:
I have a `proto-compiler` crate to re/generate the protobuf types for each new version of the application. (This is maybe once a month or when updates come in.) Relevant piece of code here: https://github.com/informalsystems/tendermint-rs/blob/0b1962a6fb985830fd3fe610df54bd6aa2e0c097/proto-compiler/src/main.rs#L43-L64

You can then copy the generated files into your application, into a subfolder and add them via `lib.rs` and use them directly. (Example here: https://github.com/informalsystems/tendermint-rs/tree/master/proto/src) My IDE loves it, I get suggestion to the generated types, since they are static files now.

The important thing is that you can't build+use protobuf structs within the same application without `build.rs`. If you separate generation to a separate application, because your protobuf messages don't change that often, then you can safely run a separate app and use "ahead of time" generated code, as you put it.
