### ISSUE TITLE
Package shouldn't be required

### ISSUE THREAD

**Issue by maxlambrecht** [tokio-rs/prost#426]
The [protocol-buffers](https://developers.google.com/protocol-buffers/docs/proto3) states: _You can add an optional package specifier to a .proto file_. 

As  _prost_ is requiring a `package` , correct proto files missing the package can't be processed. This is a limitation and impacts interoperability. 

Solution: use `option rust_package = "helloworld"` for the rust package. This is analogous to what other libraries in other languages use, like `go_package`, `java_package`, etc.

**Comment by maxlambrecht** [comment]
The use-case I have is creating a client library for the [SPIFFE](https://github.com/spiffe) Workload API: https://github.com/spiffe/go-spiffe/blob/master/proto/spiffe/workload/workload.proto

**Comment by JanBeh** [comment]
Not sure if this problem still exists. If your proto file doesn't contain a package name, it will be written to `_.rs` in the `out/` directory during the build process, which is awkward. You can use [`prost_build::Config::default_package_name`](https://docs.rs/prost-build/0.11.6/prost_build/struct.Config.html#method.default_package_filename) to fix this. Note that this method doesn't seem to expect the `.rs` file name extension to be part of the argument, which isn't documented properly yet. I generally think that it's better to include a path in the build script rather than modifying the proto file for anything Rust related. See also [this post](https://users.rust-lang.org/t/protocol-buffers-in-rust-what-to-use-and-how-to-use-it/88647/4?u=jbe) on URLO.

**Comment by caspermeijn** [comment]
It seems there are test cases to verify that a proto without package compiles. If you are still experiencing problems, please re-open this issue.
