### ISSUE TITLE
Add ability to detect unknown fields

### ISSUE THREAD

**Issue by akhilles** [tokio-rs/prost#451]
This is useful when handling untrusted inputs. E.g. a client could pack extra fields into messages in order to increase server load. Enforcing a max size limit can help, but it wouldn't address the more subtle cases.

This also allows applications to opt out of forward compatibility and having to deal with unknown fields downstream.

Related to https://github.com/danburkert/prost/issues/2.

**Comment by danburkert** [comment]
What do you expect `prost` to do here, beyond what's outlined in #2?  Is the idea that unknown fields should fail the decoding?  That's a non-starter, it would hamper forwards compatibility guarantees.

**Comment by danburkert** [comment]
> wouldn't address the more subtle cases

What cases?

**Comment by danburkert** [comment]
Protecting against untrusted clients needs to be handled at a layer outside of `prost`.  `prost` only decodes messages from byte buffers, so if you are calling decode the untrusted and potentially too-big input has already been pulled into memory, and any damage it would do, like an OOM scenario, has already been done.  This is why e.g. gRPC allows a server to set a max message size, it should enforce that max message size without requiring resources to be allocated for a message exceeding the size.

**Comment by danburkert** [comment]
Sounds like you are hinting at a second scenario where the server is running an older version of your software, and you want to protect against a client sending a critical new field, and the server silently dropping that. In effect, how to handle adding a new field to an existing message and ensuring it's respected on the server, regardless of version skew.  The answer to this is not rejecting all unknown fields, but instead something along the lines of protocol versioning or feature flag negotiation.  Again, this is something that would live outside of `prost`.

**Comment by cortopy** [comment]
I've just started using prost to decode messages coming from a Kafka topic. My use case is not so much about untrusted sources, but schema evolution.

For example, a producer sends a message with proto schema version 2, and consumer is still using schema version 1. The schema is forward compatible, meaning the only change is a new optional field in v2. 

Reading this issue, it sounds like prost will fail because the buffer is too big? But according to the specs this schema evolution should simply lead to the new field being ignored: https://developers.google.com/protocol-buffers/docs/overview#updating

I would expect either:
- a silent ignore like the specs say (maybe as a config parameter somewhere for backward compatibility?)
- some kind of extra information that could be inspected and is harmless. For example, protofish goes with this option and puts extra fields in a `garbage` field: https://docs.rs/protofish/0.3.1/protofish/decode/struct.MessageValue.html

**Comment by HayleyDeckers** [comment]
We would also be interested being able to detect the presence of unknown fields, or outright reject to parse unknown data. 

Our use-case would be a receiver of a protocol that is not under our control and of which we only support a sub-set.  Since we don't control the protocol, or the sender-side software, we can not implement any fixes at the protocol level and we are left with three solution:

1. reject unknown fields all together,
2. manually check every messages we receive,
3. silently accept unknown fields

Of these 3, the first one seems to most robust solution.

It'd be willing to work on a PR to add a 'strict mode' or a similar solution, if you'd be willing to consider merging it.

**Comment by caspermeijn** [comment]
I feel like if #2 is implemented, then unknown fields can be detected. Closing this issue in favor of #2
