### ISSUE TITLE
Merging does not reset fields in case of default values

### ISSUE THREAD

**Issue by roncohen** [tokio-rs/prost#472]
`merge` is a nice way to avoid unnecessary allocations when reading messages from a buffer. Unfortunately, when merging from a buffer, fields do not get reset on the merged object when the fields on the Protobuf objects encoded in the buffer had their default values. This results in surprising special cases as seen below:

```
message ProstMessage {
  uint32 int_value = 1;
  bytes byte_value = 2;
}
```

```rust
#[test]
fn test_prost_merge() {
    let mut reused_msg = ProstMessage {
        int_value: 1,
        byte_value: b"value".to_vec(),
    };

    let msg_with_default_values = ProstMessage {
        int_value: 2,
        byte_value: Vec::new(),
    };

    let mut buf = Vec::new();
    msg_with_default_values.encode(&mut buf).unwrap();

    // `reused_msg.int_value` now contains 2 while `byte_value` has not been reset and still contains b"value".
    reused_msg.merge(buf.as_slice()).unwrap();
    assert_eq!(reused_msg, msg_with_default_values);
}
```

prost version: 0.7.0
Thank you for your work on Prost!

**Comment by roncohen** [comment]
I found `clear()` which seems to be the way to go. I think a little note in the `merge` documentation would suffice to mitigate the surprise. If you agree, I'm happy to take go at it.

**Comment by tv42** [comment]
I think the behavior observed is because in proto3, default value is just an omitted field, like proto2 optional fields. On the wire, there's no difference between proto2 optional field that is not present and a proto3 field that is at the default value. There's not much prost can do here.

I believe the canonical workaround is to box the field (add an extra message layer), e.g. https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Int64Value

**Comment by caspermeijn** [comment]
I think you describe  exactly the expected behavior of `merge()`. If you feel like the documentation is missing something, then I would love to see a PR.
