### ISSUE TITLE
`::prost` not fully compatible with Rust-2018 project

### ISSUE THREAD

**Issue by evergreen-trading-systems** [tokio-rs/prost#500]
Prost_build generates code that imports `prost` by `::prost`, which expects the main compiling package to have it as a direct dependency. 

My project imports `prost` from another package, so when the main package compiles protos, `::prost` cannot be found. If `::prost` was changed to `crate::prost`, it would be found.

According to https://doc.rust-lang.org/reference/visibility-and-privacy.html#pubin-path-pubcrate-pubsuper-and-pubself, `::prost` is not Rust-2018 code which is why I think I have this problem.

Is it possible to use `prost` from a package that does not compile the protos?

Related
https://github.com/hyperium/tonic/issues/699
https://github.com/tokio-rs/prost/pull/488#issuecomment-875993267

**Comment by tv42** [comment]
On my first experiment with prost, this hurt me because I tried to `include!` the generated code from the main.rs, which builds as a different crate and thus didn't have the prost dependency. Moving that to lib.rs helped.

**Comment by LucioFranco** [comment]
If we had `crate::prost` it would require every user to have a `prost` module at the root of their crate, which isn't ideal. The `::prost` syntax is still valid iirc.

That said, you should be able to import the same version of prost at the root of your crate and it will not add any extra compile time since its already brought in by another crate.

As far as I know the `::` synatx will be supported in rust 2021 as well, so I don' think it makes sense to change this.
