### ISSUE TITLE
Documentation request: Kind::NullValue i32 field

### ISSUE THREAD

**Issue by davechallis** [tokio-rs/prost#631]
The enum [Kind::NullValue](https://docs.rs/prost-types/latest/prost_types/value/enum.Kind.html#variant.NullValue) variant for `prost_types::Kind` is defined as `prost_types::Kind::NullValue(i32)`.

Some clarification in the docs would be useful to explain what the `i32` value is used for here, and what values are recommended to set it to when creating an enum variant of this type.

**Comment by LucioFranco** [comment]
The `NullValue` in https://github.com/tokio-rs/prost/blob/fc9fbd9823f93774004975f7794dac112a2ff4ef/prost-build/third-party/include/google/protobuf/struct.proto#L84 is an enum and within the Kind message its a oneof so its represented as a i32 since this is how prost represents enums. As for the docs, the docs used are straight from the protobuf code.

**Comment by davechallis** [comment]
Thanks, I didn't realise this was auto-generated. Looking at the source, it seems I should set this to 0 when creating `prost_types::Kind::NullValue` in this case.
