### ISSUE TITLE
prost-build occasionally fails to compile protobuf C++

### ISSUE THREAD

**Issue by benesch** [tokio-rs/prost#653]
In v0.10, we're seeing `prost-build` occasionally fail to compile protobuf from source. We've now seen this in two projects with entirely different build systems (MaterializeInc/materialize and our internal cloud codebase), which makes me think it's not a bug in our build system. The only commonality is in that in both cases we're compiling inside of Docker. Here's two representative examples:

* https://gist.github.com/antifuchs/bfb4b8e1dc673ce7a09deb5b7c43bfcd
* https://buildkite.com/materialize/tests/builds/34688#9076b67a-eae2-41f6-b144-8483d97f5c15

I have a few separate thoughts here!

 * Is CMake even supported for building protobuf on Unix machines? The [docs](https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md) seem to suggest that the CMake build system exists to support compilation on Windows. 
 * In our [protobuf-src](https://github.com/MaterializeInc/rust-protobuf-native/tree/master/protobuf-src) crate, we use the autotools build system instead, because it seems to be the officially supported way to compile protobuf on Unix. That was stable in CI for us for several months, when we'd forked prost to use [protobuf-src](https://github.com/MaterializeInc/rust-protobuf-native/tree/master/protobuf-src). 
 * If you don't want to switch to the autotools system, is there some way to turn off compilation of the unit tests? That's what seems to fail most readily. 
 * It'd be great to eventually have prost-build use protobuf-src rather than managing its own protoc compilation. That way projects that use protoc outside of prost only need to compile protobuf from source once. We'd be happy to transfer ownership of protobuf-src to Tokio if that's a supply chain concern.

**Comment by LucioFranco** [comment]
Right, I will say I am not a c++ build tool expert and it could totally be that cmake has some issues on non-windows builds. Though I don't know why 😆 

> In our [protobuf-src](https://github.com/MaterializeInc/rust-protobuf-native/tree/master/protobuf-src?rgh-link-date=2022-05-21T15%3A50%3A52Z) crate, we use the autotools build system instead, because it seems to be the officially supported way to compile protobuf on Unix. That was stable in CI for us for several months, when we'd forked prost to use [protobuf-src](https://github.com/MaterializeInc/rust-protobuf-native/tree/master/protobuf-src?rgh-link-date=2022-05-21T15%3A50%3A52Z).

The reason I didn't go with `protobuf-src` is because I wanted to control the version of protobuf being included and not depend on a separately owned crate that is quite critical to the build process. I would be happy to give you access/take ownership of the protobuf-src crate and move it into here. Let me know if you want to coordinate here.

> f you don't want to switch to the autotools system, is there some way to turn off compilation of the unit tests? That's what seems to fail most readily.

Would https://github.com/tokio-rs/prost/pull/620 work for your use case instead of autotools? Or is this a case where we want to support different ways to fetch `protoc`.

https://github.com/tokio-rs/prost/issues/624 mentions to make `prost-build` more modular with respect to how we fetch `protoc`. 

> Is there some way to turn off compilation of the unit tests?

Which unit tests are you referring too?

> It'd be great to eventually have prost-build use protobuf-src rather than managing its own protoc compilation. That way projects that use protoc outside of prost only need to compile protobuf from source once. We'd be happy to transfer ownership of protobuf-src to Tokio if that's a supply chain concern.

Yeah, lets do it, would yall be interested in helping maintain it at all?

**Comment by ricnewton** [comment]
FYI you can turn off unit tests like this: https://github.com/tokio-rs/prost/compare/master...ricnewton:master

I can raise a PR but was waiting for outcome of https://github.com/tokio-rs/prost/pull/620

**Comment by LucioFranco** [comment]
#657 fixes this
